# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget push pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  publish-contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_PATH: Database.UnitOfWork.Contracts/Database.UnitOfWork.Contracts.csproj
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $PROJECT_PATH --configuration Release
    - name: Create package
      run: dotnet pack $PROJECT_PATH --output . --configuration Release
    - name: Push package
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  publish-entityframework:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env: 
      PROJECT_PATH: Database.UnitOfWork.EF/Database.UnitOfWork.EF.csproj
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $PROJECT_PATH --configuration Release
    - name: Create package
      run: dotnet pack $PROJECT_PATH --output . --configuration Release
    - name: Push package
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  publish-entityframework-dependencyinjection:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_PATH: Database.UnitOfWork.EF.DI/Database.UnitOfWork.EF.DI.csproj
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $PROJECT_PATH --configuration Release
    - name: Create package
      run: dotnet pack $PROJECT_PATH --output . --configuration Release
    - name: Push package
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  publish-dapper:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_PATH: Database.UnitOfWork.Dapper/Database.UnitOfWork.Dapper.csproj
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $PROJECT_PATH --configuration Release
    - name: Create package
      run: dotnet pack $PROJECT_PATH --output . --configuration Release
    - name: Push package
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
  publish-dapper-dependencyinjection:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_PATH: Database.UnitOfWork.Dapper.DI/Database.UnitOfWork.Dapper.DI.csproj
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build $PROJECT_PATH --configuration Release
    - name: Create package
      run: dotnet pack $PROJECT_PATH --output . --configuration Release
    - name: Push package
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
